### ISSUE TITLE
[BUG] <title>websocket plugin returns error code 1002

### ISSUE THREAD

**Issue by PeaceStefanYO** [apache/shenyu#2960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Got a 1002 error code (1002 Protocol Error:Server internal error)

### Expected Behavior

Shenyu websocket plugin can work as a proxy to an live wss endpoint well.

### Steps To Reproduce

1 Building up a websocket proxy to a live wss "wss://ws2.zoomex.com/realtime?v=2&timestamp=1645693331100"
My Selector configs are:
host=ws2.zoomex.com
ip:port=ws2.zoomex.com
protocol=wss://
2 Local test by using a websocket client calling "ws://127.0.0.1:9195/realtime?v=2&timestamp=1645693331100"

### Environment

```markdown
ShenYu version(s):2.4.3-SNAPSHOT
```

### Debug logs

2022-03-01 22:47:52 [boundedElastic-1] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - websocket selector success match , selector name :zoomex-websocket
2022-03-01 22:47:52 [boundedElastic-1] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - websocket rule success match , rule name :/realtime
2022-03-01 22:47:52 [boundedElastic-1] INFO  org.apache.shenyu.plugin.websocket.WebSocketPlugin - you websocket urlPath is :wss://ws2.zoomex.com/realtime?v=2&timestamp=1645693331100
2022-03-01 22:47:54 [reactor-http-kqueue-1] WARN  reactor.netty.http.client.HttpClientConnect - [id: 0x928ad654, L:/192.168.0.104:61118 - R:ws2.zoomex.com/210.71.196.201:443] The connection observed an error
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: Invalid handshake response getStatus: 403 Forbidden
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:267)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:303)
	at reactor.netty.http.client.WebsocketClientOperations.onInboundNext(WebsocketClientOperations.java:117)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:381)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:211)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by PeaceStefanYO** [comment]
And I also wanna know why in websocket plugin, a block of java code do a header filter with "sec-websocket" start with.

**Comment by yu199195** [comment]
can you config to  ws:// ，  

Why do you think can be support wss? What is the difference between ws and wss?

**Comment by PeaceStefanYO** [comment]
This can be make a improvement that allowing reset ws header "host".As I tested it in a local env so that "127.0.0.1" will passed by to the target wss://xxx.zoomex.com.So changed websocket plugin code to force re-set host into "xxx.zoomex.com" instead of "127.0.0.1",this works well, THX!

**Comment by PeaceStefanYO** [comment]
> 

Yeah,I've done it like this.Every thing goes well!
