### ISSUE TITLE
[BUG] web page error

### ISSUE THREAD

**Issue by li-keguo** [apache/shenyu#3058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in admin web page 

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/33576070/159011167-f20c9679-9ccc-4954-b096-7ba47bd3e827.png">

### Expected Behavior

normal display page

### Steps To Reproduce

step 1: login 
step 2: long time(token expired)
step 3: The page automatically jumps to the login，click login 
steo 4:  login is success, bug page is loading ......
step 5: in console is error

### Environment

```markdown
ShenYu version(s):current master
```

### Debug logs

```
index.2882ca83.js:18 uncaught at a at a 
 at t 
 at takeEvery(global/fetchPermission, t) 
 at t 
 at t 
 Error: TypeError: Cannot read properties of undefined (reading 'code')
    at http://localhost:9095/index.2882ca83.js:18:1644358
    at r (http://localhost:9095/index.2882ca83.js:18:212622)
    at Generator._invoke (http://localhost:9095/index.2882ca83.js:18:213688)
    at Generator.next (http://localhost:9095/index.2882ca83.js:18:212802)
    at u (http://localhost:9095/index.2882ca83.js:18:1590487)
    at n (http://localhost:9095/index.2882ca83.js:18:1591161)
    at http://localhost:9095/index.2882ca83.js:18:2419508
    at http://localhost:9095/index.2882ca83.js:18:1744805
    at o (http://localhost:9095/index.2882ca83.js:18:2419531)
    at http://localhost:9095/index.2882ca83.js:18:2585255
    at r (http://localhost:9095/index.2882ca83.js:18:1153922)
    at Generator._invoke (http://localhost:9095/index.2882ca83.js:18:1154967)
    at Generator.e.<computed> [as throw] (http://localhost:9095/index.2882ca83.js:18:1154101)
    at u (http://localhost:9095/index.2882ca83.js:18:1590343)
    at Object.n [as cont] (http://localhost:9095/index.2882ca83.js:18:1591161)
    at g (http://localhost:9095/index.2882ca83.js:18:1590977)
d @ index.2882ca83.js:18
Z @ index.2882ca83.js:18
g @ index.2882ca83.js:18
r @ index.2882ca83.js:18
e.cont @ index.2882ca83.js:18
g @ index.2882ca83.js:18
r @ index.2882ca83.js:18
e.cont @ index.2882ca83.js:18
g @ index.2882ca83.js:18
r @ index.2882ca83.js:18
e.cont @ index.2882ca83.js:18
g @ index.2882ca83.js:18
r @ index.2882ca83.js:18
e.cont @ index.2882ca83.js:18
u @ index.2882ca83.js:18
n @ index.2882ca83.js:18
g @ index.2882ca83.js:18
r @ index.2882ca83.js:18
e.cont @ index.2882ca83.js:18
u @ index.2882ca83.js:18
n @ index.2882ca83.js:18
g @ index.2882ca83.js:18
r @ index.2882ca83.js:18
e.cont @ index.2882ca83.js:18
u @ index.2882ca83.js:18
n @ index.2882ca83.js:18
Promise.then (async)
O @ index.2882ca83.js:18
M @ index.2882ca83.js:18
E @ index.2882ca83.js:18
u @ index.2882ca83.js:18
c @ index.2882ca83.js:18
S @ index.2882ca83.js:18
E @ index.2882ca83.js:18
u @ index.2882ca83.js:18
n @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
r @ index.2882ca83.js:18
c @ index.2882ca83.js:18
o @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
e.fetchPermissions @ index.2882ca83.js:18
value @ index.2882ca83.js:18
hn @ index.2882ca83.js:18
cr @ index.2882ca83.js:18
Rl @ index.2882ca83.js:18
to @ index.2882ca83.js:18
$r @ index.2882ca83.js:18
Wr @ index.2882ca83.js:18
Ir @ index.2882ca83.js:18
ko @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
Br @ index.2882ca83.js:18
Do @ index.2882ca83.js:18
t.render @ index.2882ca83.js:18
c @ index.2882ca83.js:18
t @ index.2882ca83.js:18
lVK7 @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
Show 36 more frames
VM2046:1          GET http://localhost:9095/platform/enum 401
(anonymous) @ VM2046:1
o @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
r @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
r @ index.2882ca83.js:18
i @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
Ue @ index.2882ca83.js:18
Ie @ index.2882ca83.js:18
M @ index.2882ca83.js:18
E @ index.2882ca83.js:18
u @ index.2882ca83.js:18
c @ index.2882ca83.js:18
S @ index.2882ca83.js:18
E @ index.2882ca83.js:18
u @ index.2882ca83.js:18
n @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
r @ index.2882ca83.js:18
c @ index.2882ca83.js:18
o @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
value @ index.2882ca83.js:18
Mr @ index.2882ca83.js:18
ao @ index.2882ca83.js:18
WifJ.t.unstable_runWithPriority @ index.2882ca83.js:18
Wt @ index.2882ca83.js:18
oo @ index.2882ca83.js:18
Wr @ index.2882ca83.js:18
Ir @ index.2882ca83.js:18
ko @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
Br @ index.2882ca83.js:18
Do @ index.2882ca83.js:18
t.render @ index.2882ca83.js:18
c @ index.2882ca83.js:18
t @ index.2882ca83.js:18
lVK7 @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
Show 20 more frames
VM2046:1          GET http://localhost:9095/plugin?currentPage=1&pageSize=50 401
(anonymous) @ VM2046:1
o @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
r @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
r @ index.2882ca83.js:18
i @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
A @ index.2882ca83.js:18
R @ index.2882ca83.js:18
M @ index.2882ca83.js:18
E @ index.2882ca83.js:18
u @ index.2882ca83.js:18
c @ index.2882ca83.js:18
S @ index.2882ca83.js:18
E @ index.2882ca83.js:18
u @ index.2882ca83.js:18
n @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
r @ index.2882ca83.js:18
c @ index.2882ca83.js:18
o @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
value @ index.2882ca83.js:18
Mr @ index.2882ca83.js:18
ao @ index.2882ca83.js:18
WifJ.t.unstable_runWithPriority @ index.2882ca83.js:18
Wt @ index.2882ca83.js:18
oo @ index.2882ca83.js:18
Wr @ index.2882ca83.js:18
Ir @ index.2882ca83.js:18
ko @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
Br @ index.2882ca83.js:18
Do @ index.2882ca83.js:18
t.render @ index.2882ca83.js:18
c @ index.2882ca83.js:18
t @ index.2882ca83.js:18
lVK7 @ index.2882ca83.js:18
t @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
(anonymous) @ index.2882ca83.js:18
Show 20 more frames
:9095/#/user/login:1 Error handling response: TypeError: self.processResponse is not a function
    at chrome-extension://cmkdbmfndkfgebldhnkbfhlneefdaaip/js/notification.js:154:10
```

**Comment by li-keguo** [comment]
clean cache is ok
