### ISSUE TITLE
[BUG] java.lang.IllegalStateException: Only one connection receive subscriber allowed.

### ISSUE THREAD

**Issue by g0715158** [apache/shenyu#3285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

http://localhost:9195/SERVER_PREGG_001/com.newland.server_preprocess.api.IPretreatProcOperationApi/1.0.0/process

tools：postman
post -raw-json(application/json)

### Environment

```markdown
ShenYu version(s):2.4.1
```

### Debug logs

2022-04-20 14:52:06 [shenyu-netty-epoll-4] ERROR org.apache.shenyu.web.handler.GlobalErrorHandler - [724a1118] Resolved [IllegalStateException: Only one connection receive subscriber allowed.] for HTTP POST /SERVER_PREGG_001/com.newland.server_preprocess.api.IPretreatProcOperationApi/1.0.0/process
2022-04-20 14:52:06 [shenyu-netty-epoll-4] DEBUG org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler - [724a1118] Resolved [IllegalStateException: Only one connection receive subscriber allowed.] for HTTP POST /SERVER_PREGG_001/com.newland.server_preprocess.api.IPretreatProcOperationApi/1.0.0/process
2022-04-20 14:52:06 [shenyu-netty-epoll-4] ERROR org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler - [724a1118]  500 Server Error for HTTP POST "/SERVER_PREGG_001/com.newland.server_preprocess.api.IPretreatProcOperationApi/1.0.0/process"
java.lang.IllegalStateException: Only one connection receive subscriber allowed.
        at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:301)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        |_ checkpoint ⇢ org.apache.shenyu.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.apache.shenyu.web.filter.FileSizeFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.apache.shenyu.bootstrap.filter.HealthFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.apache.shenyu.web.filter.CrossFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.apache.shenyu.web.filter.LocalDispatcherFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP POST "/SERVER_PREGG_001/com.newland.server_preprocess.api.IPretreatProcOperationApi/1.0.0/process" [ExceptionHandlingWebHandler]
Stack trace:
                at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:301)
                at reactor.netty.channel.FluxReceive.subscribe(FluxReceive.java:134)
                at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53)
                at reactor.netty.ByteBufFlux.subscribe(ByteBufFlux.java:329)
                at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53)
                at reactor.netty.ByteBufFlux.subscribe(ByteBufFlux.java:329)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
                at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:218)
                at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:351)
                at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:348)
                at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:458)
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:89)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:211)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
                at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
                at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
                at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
                at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:748)

**Comment by yu199195** [comment]
Are you using the official release package for the deployment?  

> https://archive.apache.org/dist/incubator/shenyu/2.4.1/

What is your request?

**Comment by g0715158** [comment]
download  code and package

**Comment by yu199195** [comment]
How did you request ?  maybe config this  in shenyu-bootstrap yaml：

```
shenyu
  file:
    enabled: false
```

**Comment by g0715158** [comment]
@yu199195 I tried it but it didn't work
