### ISSUE TITLE
error occurs when grpc lib update to 1.45.1

### ISSUE THREAD

**Issue by ljwhx2002** [apache/shenyu#3344]
### Question

select name： /grpc

 <grpc.version>1.45.1</grpc.version>

java.lang.IllegalArgumentException: Invalid DNS name: /grpc
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at io.grpc.internal.DnsNameResolver.<init>(DnsNameResolver.java:171)
	at io.grpc.grpclb.GrpclbNameResolver.<init>(GrpclbNameResolver.java:57)
	at io.grpc.grpclb.SecretGrpclbNameResolverProvider$Provider.newNameResolver(SecretGrpclbNameResolverProvider.java:67)
	at io.grpc.grpclb.SecretGrpclbNameResolverProvider$Provider.newNameResolver(SecretGrpclbNameResolverProvider.java:48)
	at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:168)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:771)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:785)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:665)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at org.apache.shenyu.plugin.grpc.client.GrpcClientBuilder.buildClient(GrpcClientBuilder.java:76)

**Comment by hutaishi** [comment]
Thanks for the feedback, I will test this.
