### ISSUE TITLE
[BUG] <thread locked>

### ISSUE THREAD

**Issue by mahaitao617** [apache/shenyu#3736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

version 2.4.3
![image](https://user-images.githubusercontent.com/12776225/180138125-2fd4e0ac-9d81-4478-9caa-0a96be4e6a37.png)
![Uploading image.png…]()
method parallelStream maybe make thread locked

### Expected Behavior

![Uploading image.png…]()

### Steps To Reproduce

use httpsync 

### Environment

```markdown
ShenYu version(s):2.4.3
```

### Debug logs

通过thread -b可以看到有线程阻塞，日志如下：
thread -b
"main" Id=1 WAITING on java.util.stream.ReduceOps$ReduceTask@791e6283
    at java.lang.Object.wait(Native Method)
    -  waiting on java.util.stream.ReduceOps$ReduceTask@791e6283
    at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:334)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
    at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
    at org.apache.shenyu.sync.data.http.refresh.DataRefreshFactory.executor(DataRefreshFactory.java:64)
    at org.apache.shenyu.sync.data.http.HttpSyncDataService.updateCacheWithJson(HttpSyncDataService.java:184)
    at org.apache.shenyu.sync.data.http.HttpSyncDataService.doFetchGroupConfig(HttpSyncDataService.java:164)
    at org.apache.shenyu.sync.data.http.HttpSyncDataService.fetchGroupConfig(HttpSyncDataService.java:129)
    at org.apache.shenyu.sync.data.http.HttpSyncDataService.start(HttpSyncDataService.java:113)
    at org.apache.shenyu.sync.data.http.HttpSyncDataService.<init>(HttpSyncDataService.java:98)
    at org.apache.shenyu.springboot.starter.sync.data.http.HttpSyncDataConfiguration.httpSyncDataService(HttpSyncDataConfiguration.java:61)
    at org.apache.shenyu.springboot.starter.sync.data.http.HttpSyncDataConfiguration$$EnhancerBySpringCGLIB$$faa066b3.CGLIB$httpSyncDataService$0(<generated>)
    at org.apache.shenyu.springboot.starter.sync.data.http.HttpSyncDataConfiguration$$EnhancerBySpringCGLIB$$faa066b3$$FastClassBySpringCGLIB$$a6579390.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
    at org.apache.shenyu.springboot.starter.sync.data.http.HttpSyncDataConfiguration$$EnhancerBySpringCGLIB$$faa066b3.httpSyncDataService(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
    at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$190/1587872480.getObject(Unknown Source)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
    -  locked java.util.concurrent.ConcurrentHashMap@18b30253 <---- but blocks 1 other threads!
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
    -  locked java.lang.Object@2185cf02
    at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
    at org.apache.shenyu.bootstrap.ShenyuBootstrapApplication.main(ShenyuBootstrapApplication.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

**Comment by yu199195** [comment]
can you fix it？

**Comment by mahaitao617** [comment]
ok i pull a pr to fix it

**Comment by mahaitao617** [comment]
the branch master have fixed
