### ISSUE TITLE
when http calls dubbo, the body is blank and the error is reported

### ISSUE THREAD

**Issue by xugflz2011** [apache/shenyu#3808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.dubbo接口为有参接口
2.http请求中body传{}报错,传(加一个空格){ }正常.

### Expected Behavior

当dubbo接口有参数,而http传的空或""或{ }或{} 或{\n\r}一类的,可以调用到对应的dubbo接口,不对dubbo接口的参数对象进行赋值

### Environment

```markdown
ShenYu version(s):
2.4.3  gateway
```

### Debug logs

org.apache.dubbo.rpc.RpcException: com.cloudstore.upms.admin.facade.ProjectAdminFacade.projectGetListReq()
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:195)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:321)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:54)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:321)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:321)
	at org.apache.dubbo.rpc.filter.ProfilerServerFilter.invoke(ProfilerServerFilter.java:58)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:321)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:193)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:153)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: com.cloudstore.upms.admin.facade.ProjectAdminFacade.projectGetListReq()
	at java.lang.Class.getMethod(Class.java:1786)
	at org.apache.dubbo.common.utils.ReflectUtils.findMethodByMethodSignature(ReflectUtils.java:923)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:89)
	... 17 more
] for HTTP POST /upms-dubbo/admin/project/getList

**Comment by yu199195** [comment]
pls modify issue tilte to english

**Comment by dragon-zhang** [comment]
try with `{ }`

**Comment by xugflz2011** [comment]
{    }  or {\n\r} is ok

**Comment by dragon-zhang** [comment]
see https://github.com/apache/shenyu/pull/4064
