### ISSUE TITLE
[BUG] LocalPluginController#deleteRule causes removeCacheData NPE

### ISSUE THREAD

**Issue by yunlongn** [apache/shenyu#3821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I tested LocalPluginController#deleteRule, I found the removeCacheData null pointer

![image](https://user-images.githubusercontent.com/38271111/183576671-9f53cd5f-2029-4e81-9394-72673c38e4f7.png)

![image](https://user-images.githubusercontent.com/38271111/183576776-8829e12f-1a88-4130-bdca-989d06bf0da9.png)

removeCacheData uses ruleData.getPluginName(), but LocalPluginController#deleteRule builds empty

### Expected Behavior

I think the pluginName parameter needs to be added to LocalPluginController#deleteRule

### Environment

```markdown
ShenYu version(s):
```

**Comment by yunlongn** [comment]
Please assigne to me.

**Comment by moremind** [comment]
this is debug log:

2022-08-09 14:11:05 [WebSocketConnectReadThread-262] ERROR org.java_websocket.drafts.Draft_6455 - Runtime exception during onWebsocketMessage
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.shenyu.plugin.base.cache.CommonPluginDataSubscriber.removeCacheData(CommonPluginDataSubscriber.java:245)
	at org.apache.shenyu.plugin.base.cache.CommonPluginDataSubscriber.lambda$subscribeDataHandler$4(CommonPluginDataSubscriber.java:165)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.shenyu.plugin.base.cache.CommonPluginDataSubscriber.subscribeDataHandler(CommonPluginDataSubscriber.java:165)
	at org.apache.shenyu.plugin.base.cache.CommonPluginDataSubscriber.unRuleSubscribe(CommonPluginDataSubscriber.java:143)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.shenyu.plugin.sync.data.websocket.handler.RuleDataHandler.doDelete(RuleDataHandler.java:54)
	at org.apache.shenyu.plugin.sync.data.websocket.handler.AbstractDataHandler.handle(AbstractDataHandler.java:80)
	at org.apache.shenyu.plugin.sync.data.websocket.handler.WebsocketDataHandler.executor(WebsocketDataHandler.java:59)
	at org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient.handleResult(ShenyuWebsocketClient.java:161)
	at org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient.onMessage(ShenyuWebsocketClient.java:112)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:591)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:508)
	at java.lang.Thread.run(Thread.java:750)
2022-08-09 14:11:05 [WebSocketConnectReadThread-262] ERROR org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket server[ws://localhost:9095/websocket] is error.....
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.shenyu.plugin.base.cache.CommonPluginDataSubscriber.removeCacheData(CommonPluginDataSubscriber.java:245)
	at org.apache.shenyu.plugin.base.cache.CommonPluginDataSubscriber.lambda$subscribeDataHandler$4(CommonPluginDataSubscriber.java:165)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.shenyu.plugin.base.cache.CommonPluginDataSubscriber.subscribeDataHandler(CommonPluginDataSubscriber.java:165)
	at org.apache.shenyu.plugin.base.cache.CommonPluginDataSubscriber.unRuleSubscribe(CommonPluginDataSubscriber.java:143)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.shenyu.plugin.sync.data.websocket.handler.RuleDataHandler.doDelete(RuleDataHandler.java:54)
	at org.apache.shenyu.plugin.sync.data.websocket.handler.AbstractDataHandler.handle(AbstractDataHandler.java:80)
	at org.apache.shenyu.plugin.sync.data.websocket.handler.WebsocketDataHandler.executor(WebsocketDataHandler.java:59)
	at org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient.handleResult(ShenyuWebsocketClient.java:161)
	at org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient.onMessage(ShenyuWebsocketClient.java:112)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:591)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:508)
	at java.lang.Thread.run(Thread.java:750)
