### ISSUE TITLE
[BUG] When client properties is null or invalid while throw NullPointException

### ISSUE THREAD

**Issue by MiracleDx** [apache/shenyu#3862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When client property is null or invalid while throw NullPointException

![iShot_2022-08-19_09 24 26](https://user-images.githubusercontent.com/25627222/185522364-288b5297-40ea-4285-8a39-546ec373108a.png)

### Expected Behavior

exception message should be more explicit

### Environment

```markdown
ShenYu version(s): 2.4.3
```

### Debug logs

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springCloudClientBeanPostProcessor' defined in class path resource [org/apache/shenyu/springboot/starter/client/springcloud/ShenyuSpringCloudClientConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shenyu.client.springcloud.init.SpringCloudClientBeanPostProcessor]: Factory method 'springCloudClientBeanPostProcessor' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1341) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:241) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at com.picc.saas.facade.FacadeApplication.main(FacadeApplication.java:14) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shenyu.client.springcloud.init.SpringCloudClientBeanPostProcessor]: Factory method 'springCloudClientBeanPostProcessor' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.apache.shenyu.client.springcloud.init.SpringCloudClientBeanPostProcessor.<init>(SpringCloudClientBeanPostProcessor.java:90) ~[shenyu-client-springcloud-2.4.3.jar:2.4.3]
	at org.apache.shenyu.springboot.starter.client.springcloud.ShenyuSpringCloudClientConfiguration.springCloudClientBeanPostProcessor(ShenyuSpringCloudClientConfiguration.java:50) ~[shenyu-spring-boot-starter-client-springcloud-2.4.3.jar:2.4.3]
	at org.apache.shenyu.springboot.starter.client.springcloud.ShenyuSpringCloudClientConfiguration$$EnhancerBySpringCGLIB$$91e84c4d.CGLIB$springCloudClientBeanPostProcessor$1(<generated>) ~[shenyu-spring-boot-starter-client-springcloud-2.4.3.jar:2.4.3]
	at org.apache.shenyu.springboot.starter.client.springcloud.ShenyuSpringCloudClientConfiguration$$EnhancerBySpringCGLIB$$91e84c4d$$FastClassBySpringCGLIB$$fd4960cd.invoke(<generated>) ~[shenyu-spring-boot-starter-client-springcloud-2.4.3.jar:2.4.3]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.shenyu.springboot.starter.client.springcloud.ShenyuSpringCloudClientConfiguration$$EnhancerBySpringCGLIB$$91e84c4d.springCloudClientBeanPostProcessor(<generated>) ~[shenyu-spring-boot-starter-client-springcloud-2.4.3.jar:2.4.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	... 21 common frames omitted

**Comment by MiracleDx** [comment]
![image](https://user-images.githubusercontent.com/25627222/185819002-aa50d786-91d3-44f1-9c89-85a073ed2408.png)
if i used dubbo, but i didn't use dubbo config, it will be throw explicited message of exception, not for NullPointException,  it also will improve mistakes of #3865 , i used springCloud met this error too, but if had this explicited message, could be used quickly

**Comment by MiracleDx** [comment]
> 

About #3863

**Comment by yu199195** [comment]
hi， thanks for you contributor
