### ISSUE TITLE
websocket plugin data is empty

### ISSUE THREAD

**Issue by Layfolk-zcy** [apache/shenyu#4302]
### Question

shenyu version-2.5.0

**shenyu Admin and gateway  data sync by nacos**

when i run websocket example project that selector data is empty in proxy of pluginList.

In the picture, the data is inserted by myself
![image](https://user-images.githubusercontent.com/59356890/211254036-5384936d-4faa-4ef0-b9a0-7ae2df37e745.png)
![image](https://user-images.githubusercontent.com/59356890/211254235-3be72f12-f0d0-4d32-b38f-8796cf9155ff.png)
![image](https://user-images.githubusercontent.com/59356890/211254254-abc57834-41c5-44c1-94d7-57ee5e9104b7.png)

this is a result by postman.
![image](https://user-images.githubusercontent.com/59356890/211254081-9dd6e05b-1322-40f4-b1d2-4005c26f6af9.png)

this is config of websocket server
![image](https://user-images.githubusercontent.com/59356890/211254186-92672305-a5e7-437a-b1da-3cc106a097e7.png)

error infomation
```java
2023-01-09 15:07:32 [parallel-5] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - websocket selector success match , selector name :/ws-annotation
2023-01-09 15:07:32 [parallel-5] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - websocket rule success match , rule name :/myWs
2023-01-09 15:07:32 [parallel-5] INFO  org.apache.shenyu.plugin.websocket.WebSocketPlugin - you websocket urlPath is :ws://172.1.11.35:8001/ws-annotation/myWs
2023-01-09 15:07:32 [reactor-http-nio-9] WARN  reactor.netty.http.client.HttpClientConnect - [8bf5dd8b-1, L:/172.1.11.35:19834 - R:/172.1.11.35:8001] The connection observed an error
io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Invalid handshake response getStatus: 404 
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:272)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:309)
	at reactor.netty.http.client.WebsocketClientOperations.onInboundNext(WebsocketClientOperations.java:116)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2023-01-09 15:07:32 [reactor-http-nio-9] WARN  reactor.netty.channel.FluxReceive - [8bf5dd8b-1, L:/172.1.11.35:19834 ! R:/172.1.11.35:8001] An exception has been observed post termination, use DEBUG level to see the full stack: io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Connection prematurely closed BEFORE opening handshake is complete.

```

**Comment by iwangjie** [comment]
Check that the IP and port mappings are correct, and try using the TELNET command to test the WS operation.

If you can not solve your problem, please try to refer to the following article, may be helpful to you
- https://github.com/spring-cloud/spring-cloud-gateway/issues/2115
- https://github.com/reactor/reactor-netty/pull/1635/commits
