### ISSUE TITLE
[BUG] shenyu-admin running by docker, edit plugin error

### ISSUE THREAD

**Issue by wklong** [apache/shenyu#4330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/11863572/213350511-ceff91fb-3613-40f1-a7ec-efce80c94d7e.png">

### Expected Behavior

Caused by: org.springframework.jdbc.BadSqlGrammarException: Error selecting key or setting result to parameter object. Cause: org.postgresql.util.PSQLException: ERROR: function last_insert_id() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: function last_insert_id() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101) ~[spring-jdbc-5.3.20.jar:5.3.20]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.20.jar:5.3.20]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79) ~[spring-jdbc-5.3.20.jar:5.3.20]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79) ~[spring-jdbc-5.3.20.jar:5.3.20]
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91) ~[mybatis-spring-2.0.7.jar:2.0.7]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441) ~[mybatis-spring-2.0.7.jar:2.0.7]
        at com.sun.proxy.$Proxy105.insert(Unknown Source) ~[na:na]
        at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272) ~[mybatis-spring-2.0.7.jar:2.0.7]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy124.insert(Unknown Source) ~[na:na]
        at org.apache.shenyu.admin.listener.RecordLogDataChangedAdapterListener.onApplicationEvent(RecordLogDataChangedAdapterListener.java:49) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.listener.RecordLogDataChangedAdapterListener.onApplicationEvent(RecordLogDataChangedAdapterListener.java:29) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.20.jar:5.3.20]
        at org.apache.shenyu.admin.service.publish.PluginEventPublisher.publish(PluginEventPublisher.java:119) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.service.publish.PluginEventPublisher.onUpdated(PluginEventPublisher.java:74) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.service.impl.PluginServiceImpl.update(PluginServiceImpl.java:222) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.service.impl.PluginServiceImpl.createOrUpdate(PluginServiceImpl.java:80) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.service.impl.PluginServiceImpl$$FastClassBySpringCGLIB$$2ab7a56a.invoke(<generated>) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.apache.shenyu.admin.service.impl.PluginServiceImpl$$EnhancerBySpringCGLIB$$8f7d0263.createOrUpdate(<generated>) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.service.impl.PluginServiceImpl$$FastClassBySpringCGLIB$$2ab7a56a.invoke(<generated>) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.apache.shenyu.admin.service.impl.PluginServiceImpl$$EnhancerBySpringCGLIB$$b3449031.createOrUpdate(<generated>) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.controller.PluginController.createPlugin(PluginController.java:123) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.controller.PluginController.updatePlugin(PluginController.java:140) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.shenyu.admin.controller.PluginController$$FastClassBySpringCGLIB$$90452f44.invoke(<generated>) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.apache.shenyu.admin.aspect.PrintApiLogAspect.logAround(PrintApiLogAspect.java:64) ~[shenyu-admin-2.5.0.jar:2.5.0]
        ... 105 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: function last_insert_id() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.5.jar:42.3.5]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[postgresql-42.3.5.jar:42.3.5]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[postgresql-42.3.5.jar:42.3.5]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490) ~[postgresql-42.3.5.jar:42.3.5]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408) ~[postgresql-42.3.5.jar:42.3.5]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167) ~[postgresql-42.3.5.jar:42.3.5]
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:156) ~[postgresql-42.3.5.jar:42.3.5]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-4.0.3.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.5.9.jar:3.5.9]
        at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy120.query(Unknown Source) ~[na:na]
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.shenyu.admin.mybatis.pg.interceptor.PostgreSQLQueryInterceptor.intercept(PostgreSQLQueryInterceptor.java:61) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy119.query(Unknown Source) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy119.query(Unknown Source) ~[na:na]
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:132) ~[pagehelper-5.3.0.jar:na]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy119.query(Unknown Source) ~[na:na]
        at org.apache.ibatis.executor.keygen.SelectKeyGenerator.processGeneratedKeys(SelectKeyGenerator.java:67) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.keygen.SelectKeyGenerator.processAfter(SelectKeyGenerator.java:54) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:51) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.5.9.jar:3.5.9]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy120.update(Unknown Source) ~[na:na]
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.5.9.jar:3.5.9]
        at sun.reflect.GeneratedMethodAccessor188.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy119.update(Unknown Source) ~[na:na]
        at org.apache.shenyu.admin.mybatis.pg.interceptor.PostgreSqlUpdateInterceptor.intercept(PostgreSqlUpdateInterceptor.java:60) ~[shenyu-admin-2.5.0.jar:2.5.0]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy119.update(Unknown Source) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor188.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64) ~[mybatis-3.5.9.jar:3.5.9]
        at com.sun.proxy.$Proxy119.update(Unknown Source) ~[na:na]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194) ~[mybatis-3.5.9.jar:3.5.9]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181) ~[mybatis-3.5.9.jar:3.5.9]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427) ~[mybatis-spring-2.0.7.jar:2.0.7]
        ... 147 common frames omitted

### Environment

```markdown
ShenYu version(s): 2.5.0
docker run,  local run no error
```

**Comment by yu199195** [comment]
Did you initialize the sql script in  shenyu/db/init/pg ?

**Comment by wklong** [comment]
> Did you initialize the sql script in shenyu/db/init/pg ?

I've done it

**Comment by wklong** [comment]
![Uploading image.png…]()
I may have found the problem, it has been fixed on May 22, 2022,V2.5.0 was deployed on August 25, 2022, you can check the docker image, thks

**Comment by wklong** [comment]
> Did you initialize the sql script in shenyu/db/init/pg ?

![image](https://user-images.githubusercontent.com/11863572/213370793-b122a95a-20a6-4e01-baaf-037a6741ab70.png)
I may have found the problem, it has been fixed on May 22, 2022,V2.5.0 was deployed on August 25, 2022, you can check the docker image, thks
