### ISSUE TITLE
[BUG] Shenyu occasionally causes CPU spikes

### ISSUE THREAD

**Issue by LiKaiping415** [apache/shenyu#4337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Shenyu occasionally causes CPU spikes
When the CPU soars, all the requests are blocked
Stack information for threads that cause CPU spikes：
java.lang.Thread.State: RUNNABLE
        at org.apache.commons.collections4.map.AbstractHashedMap.getEntry(AbstractHashedMap.java:462)
        at org.apache.commons.collections4.map.AbstractLinkedMap.getEntry(AbstractLinkedMap.java:216)
        at org.apache.commons.collections4.map.LRUMap.get(LRUMap.java:250)
        at org.apache.commons.collections4.map.LRUMap.get(LRUMap.java:233)
        at org.apache.shenyu.plugin.base.cache.MetaDataCache.obtain(MetaDataCache.java:123)
        at org.apache.shenyu.plugin.global.DefaultShenyuContextBuilder.buildData(DefaultShenyuContextBuilder.java:75)
        at org.apache.shenyu.plugin.global.DefaultShenyuContextBuilder.build(DefaultShenyuContextBuilder.java:60)
        at org.apache.shenyu.plugin.global.GlobalPlugin.execute(GlobalPlugin.java:47)
        at org.apache.shenyu.web.handler.ShenyuWebHandler$DefaultShenyuPluginChain.lambda$execute$0(ShenyuWebHandler.java:221)
        at org.apache.shenyu.web.handler.ShenyuWebHandler$DefaultShenyuPluginChain$$Lambda$1134/955660766.get(Unknown Source)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)

### Expected Behavior

Requests can be processed all the time

### Steps To Reproduce

occasionally

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

java.lang.Thread.State: RUNNABLE
        at org.apache.commons.collections4.map.AbstractHashedMap.getEntry(AbstractHashedMap.java:462)
        at org.apache.commons.collections4.map.AbstractLinkedMap.getEntry(AbstractLinkedMap.java:216)
        at org.apache.commons.collections4.map.LRUMap.get(LRUMap.java:250)
        at org.apache.commons.collections4.map.LRUMap.get(LRUMap.java:233)
        at org.apache.shenyu.plugin.base.cache.MetaDataCache.obtain(MetaDataCache.java:123)
        at org.apache.shenyu.plugin.global.DefaultShenyuContextBuilder.buildData(DefaultShenyuContextBuilder.java:75)
        at org.apache.shenyu.plugin.global.DefaultShenyuContextBuilder.build(DefaultShenyuContextBuilder.java:60)
        at org.apache.shenyu.plugin.global.GlobalPlugin.execute(GlobalPlugin.java:47)
        at org.apache.shenyu.web.handler.ShenyuWebHandler$DefaultShenyuPluginChain.lambda$execute$0(ShenyuWebHandler.java:221)
        at org.apache.shenyu.web.handler.ShenyuWebHandler$DefaultShenyuPluginChain$$Lambda$1134/955660766.get(Unknown Source)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)

### Anything else?

no

**Comment by KevinClair** [comment]
Is there Any blocked thread?

**Comment by LiKaiping415** [comment]
@KevinClair no blocked thread

**Comment by LiKaiping415** [comment]
@KevinClair Guess from the stack information that it is because the hash linked list generates rings

**Comment by KevinClair** [comment]
> @KevinClair Guess from the stack information that it is because the hash linked list generates rings

Got it, i will check it later.

**Comment by moremind** [comment]
do you have information about memory usage and cpu usage

**Comment by LiKaiping415** [comment]
> do you have information about memory usage and cpu usage

@moremind Memory is normal, GC and heap memory are normal. But the CPU soared to 200%

**Comment by KevinClair** [comment]
Perhaps you can sort by thread's CPU usage.

**Comment by LiKaiping415** [comment]
> Perhaps you can sort by thread's CPU usage.
Information has been sent to your Page's email address @KevinClair

**Comment by LiKaiping415** [comment]
> Perhaps you can sort by thread's CPU usage.

Information has been sent to your Page's email address @KevinClair

**Comment by KevinClair** [comment]
> > Perhaps you can sort by thread's CPU usage.
> 
> Information has been sent to your Page's email address @KevinClair

Got it, i will replay as soon as possible.

**Comment by KevinClair** [comment]
This problem had been fixed, see #3929 
Please update the code to new version.

**Comment by LiKaiping415** [comment]
Thank you
