### ISSUE TITLE
[Question] run ShenyuAdminBootstrap with coverage failed

### ISSUE THREAD

**Issue by comeCU** [apache/shenyu#4463]
### Question

Hi, when I run ShenyuAdminBootstrap with coverage, it failed.

```java
2023-03-09 19:10:10 [shenyu-upstream-health-check-request-3] ERROR org.apache.shenyu.admin.service.impl.UpstreamCheckService - check zombie upstream the url=192.168.31.45:8884 is fail
2023-03-09 19:10:20 [shenyu-upstream-health-check-request-5] ERROR org.apache.shenyu.common.utils.UpstreamCheckUtils - socket connect is error.
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	at java.net.Socket.connect(Socket.java:606)
	at org.apache.shenyu.common.utils.UpstreamCheckUtils.isHostConnector(UpstreamCheckUtils.java:79)
	at org.apache.shenyu.common.utils.UpstreamCheckUtils.checkUrl(UpstreamCheckUtils.java:74)
	at org.apache.shenyu.common.utils.UpstreamCheckUtils.checkUrl(UpstreamCheckUtils.java:51)
	at org.apache.shenyu.admin.service.impl.UpstreamCheckService.checkZombie0(UpstreamCheckService.java:293)
	at org.apache.shenyu.admin.service.impl.UpstreamCheckService.lambda$checkZombie$4(UpstreamCheckService.java:285)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2023-03-09 19:10:20 [shenyu-upstream-health-check-request-5] ERROR org.apache.shenyu.admin.service.impl.UpstreamCheckService - check zombie upstream the url=192.168.31.45:8884 is fail
2023-03-09 19:10:30 [shenyu-upstream-health-check-request-4] ERROR org.apache.shenyu.common.utils.UpstreamCheckUtils - socket connect is error.
java.net.ConnectException: Connection refused (Connection refused)
……
```

**Comment by iwangjie** [comment]
hi Can you provide more context?

**Comment by comeCU** [comment]
run it again, it's working.

#### Environment
```
ShenYu version(s): master
```
