### ISSUE TITLE
[BUG] <UpstreamCheckUtils#checkUrl>

### ISSUE THREAD

**Issue by zhuang0928** [apache/shenyu#4487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Because a domain name is configured that starts with http,  for example  httpdemo.big.com

[31m2023-03-16 18:10:09[0;39m [32m[shenyu-scheduled-upstream-task-1][0;39m [1;31mERROR[0;39m [1;35morg.apache.shenyu.admin.service.impl.UpstreamCheckService[0;39m - [36mupstream scheduled check error -------- 
[0;39mjava.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.shenyu.common.utils.UpstreamCheckUtils.checkUrl(UpstreamCheckUtils.java:68)
	at org.apache.shenyu.common.utils.UpstreamCheckUtils.checkUrl(UpstreamCheckUtils.java:51)
	at org.apache.shenyu.admin.service.impl.UpstreamCheckService.check(UpstreamCheckService.java:281)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.apache.shenyu.admin.service.impl.UpstreamCheckService.scheduled(UpstreamCheckService.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

### Expected Behavior

url.startsWith("http")  should be changed to  url.startsWith("http://") 
  

### Environment

```markdown
ShenYu version(s):
```

**Comment by yunlongn** [comment]
@zhuang0928  hi, can you fix it？
