### ISSUE TITLE
[BUG] <dubbo Multiple input dto parameters, json conversion error>

### ISSUE THREAD

**Issue by liaolzy** [apache/shenyu#4500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

dubbo Multiple input dto parameters, json conversion error:

public SmsResultBean<String> sendTwoDTO(ComplexBeanListDTO dto, ConfigDto configDto) ;

public class ComplexBeanListDTO implements Serializable {

	private static final long serialVersionUID = 815364191530232514L;

    private Long id;
    
    private String name;
    
	private List<DubboTest> users;
...
}

public class ConfigDto implements Serializable {

    private String myAccount;

    private String account;
..
}

### Expected Behavior

No response

### Steps To Reproduce

No response

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

023-03-24 11:41:52[0;39m [32m[shenyu-netty-nio-3][0;39m [1;31mERROR[0;39m [1;35morg.apache.shenyu.web.handler.GlobalErrorHandler[0;39m - [36mhandle error: [60a14b3f-8] Resolved [UnsupportedOperationException: JsonObject] for HTTP POST /dubbo-test/sendTwoDTO
[0;39mjava.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:179)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.apache.shenyu.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
	*__checkpoint ⇢ org.apache.shenyu.web.filter.FileSizeFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.apache.shenyu.web.filter.CrossFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/dubbo-test/sendTwoDTO" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at com.google.gson.JsonElement.getAsString(JsonElement.java:179)
		at org.apache.shenyu.common.utils.GsonUtils.jsonArrayToListInConvertToMap(GsonUtils.java:331)
		at org.apache.shenyu.common.utils.GsonUtils.convertToMap(GsonUtils.java:309)
		at org.apache.shenyu.plugin.api.utils.BodyParamUtils.lambda$0(BodyParamUtils.java:126)
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
		at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
		at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
		at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:444)
		at org.apache.shenyu.plugin.api.utils.BodyParamUtils.buildParameters(BodyParamUtils.java:132)
		at org.apache.shenyu.plugin.dubbo.common.param.DubboParamResolveServiceImpl.buildParameter(DubboParamResolveServiceImpl.java:30)
		at org.apache.shenyu.plugin.alibaba.dubbo.proxy.AlibabaDubboProxyService.genericInvoker(AlibabaDubboProxyService.java:82)
		at org.apache.shenyu.plugin.alibaba.dubbo.AlibabaDubboPlugin.lambda$0(AlibabaDubboPlugin.java:80)
		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)

### Anything else?

No response

**Comment by dragon-zhang** [comment]
check `org.apache.shenyu.plugin.api.utils.BodyParamUtils#buildParameters`

**Comment by liaolzy** [comment]
{
    "dto": {
        "name": "测试",
        "id": 1
        , "users":[{"id":"123","name":"xiaoyu"}, {"id":"1233","name":"xiaoyu2"}]
    }
    , "configDto": {
        "account": "account123",
        "messageType": "MESSAGE_TYPE_NORMAL",
        "myAccount": "myAccount123",
        "passWord": "PassWord123",
        "type": "ACCOUNT_TYPE_OA"
    }
}
--------------------------------------------
Error Source: Entering the Users Collection

**Comment by prFor** [comment]
I used the following request parameters for dubbo multiple parameters test in [2.6.0-SNAPSHOT] version and did not find this bug you mentioned, now I attach my request message. You can also test in this version to see if the problem is still there, if there is still a problem please provide more information, thanks. For example, the dubbo version.
2 list parameters:
`{
    "users":[{"id":"xxx","name":"test chenbin"},{"id":"xxx2","name":"test chenbin2"}],
    "accounts":[{
        "account":"id1123",
        "password":"123456"
    }]
}`
2个object:
`
{
    "user":{
        "id":"123",
        "name":"chenbin",
        "users":[{"id":"xxx","name":"test chenbin"}]
    },
    "account":{
        "account":"id1123",
        "password":"123456"
    }
}
`
