### ISSUE TITLE
docker启动报错

### ISSUE THREAD

**Issue by mxl530268618** [apache/shenyu#4723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2023-06-09 09:18:40 [WebSocketConnectReadThread-201] ERROR org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket server[ws://localhost:9095/websocket] is err
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
	at java.lang.Thread.run(Thread.java:748)

### Expected Behavior

2023-06-09 09:18:40 [WebSocketConnectReadThread-201] ERROR org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket server[ws://localhost:9095/websocket] is err
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
	at java.lang.Thread.run(Thread.java:748)

### Steps To Reproduce

2023-06-09 09:18:40 [WebSocketConnectReadThread-201] ERROR org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket server[ws://localhost:9095/websocket] is err
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
	at java.lang.Thread.run(Thread.java:748)

### Environment

```markdown
2023-06-09 09:18:40 [WebSocketConnectReadThread-201] ERROR org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket server[ws://localhost:9095/websocket] is err
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yu199195** [comment]
pls modify tilte （used english）

**Comment by mxl530268618** [comment]
2023-06-09 09:18:30 [WebSocketConnectReadThread-200] ERROR org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket server[ws://localhost:9095/websocket] is err
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
	at java.lang.Thread.run(Thread.java:748)
2023-06-09 09:18:30 [shenyu-shared_wheel_timer-4] WARN&nbsp; org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket connection server[ws://localhost:9095/websocket
2023-06-09 09:18:40 [WebSocketConnectReadThread-201] ERROR org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket server[ws://localhost:9095/websocket] is err
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at org.java_websocket.client.WebSocketClient.ru





马小龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月9日(星期五) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shenyu] docker启动报错 (Issue #4723)





 
pls modify tilte （used english）

**Comment by WXzhongwang** [comment]
@yu199195 any solutions here, because it seems to be the same situation which i faced now.
 https://github.com/apache/shenyu/issues/5265 
Any advices here?
