### ISSUE TITLE
[Question] grpc协议服务启动报错是什么原因

### ISSUE THREAD

**Issue by freemanxzx** [apache/shenyu#4955]
### Question

看错误应该不影响使用，主要影响服务关闭

Exception in thread "Thread-3" java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.util.IdentityHashMap java.lang.ApplicationShutdownHooks.hooks acc
essible: module java.base does not "opens java.lang" to unnamed module @1a407d53
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at org.apache.shenyu.client.core.shutdown.ShenyuClientShutdownHook$TakeoverOtherHooksThread.run(ShenyuClientShutdownHook.java:99)

**Comment by freemanxzx** [comment]
@yu199195 why did you close it?
