### ISSUE TITLE
Does Shenyu support JDK17 now?

### ISSUE THREAD

**Issue by tinybyhuang** [apache/shenyu#5317]
### Question

error message:
`
Exception in thread "Thread-47" java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.util.IdentityHashMap java.lang.ApplicationShutdownHooks.hooks accessible: module java.base does not "opens java.lang" to unnamed module @57250572
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.apache.shenyu.client.core.shutdown.ShenyuClientShutdownHook$TakeoverOtherHooksThread.run(ShenyuClientShutdownHook.java:99)
`

**Comment by yu199195** [comment]
No，mybe next version
