### ISSUE TITLE
The quickstart via Docker doesn't work: Can not find url, please check your configuration

### ISSUE THREAD

**Issue by geek-ken** [apache/shenyu#5349]
### Service
- curl
```bash
curl 192.168.10.100:8000/ken
```
- message
```
Hello, ken! 
```

### Deploy

- deploy Shenyu
```bash
sudo docker network create shenyu-quickstart
sudo docker pull apache/shenyu-bootstrap
sudo docker run -d --name shenyu-quickstart \
           -p 9195:9195        \
           -e "shenyu.local.enabled=true" \
           --network=shenyu-quickstart     \
           apache/shenyu-bootstrap
```
- add rule
```bash
sudo curl --location --request POST 'http://localhost:9195/shenyu/plugin/selectorAndRules' \
--header 'Content-Type: application/json' \
--header 'localKey: 123456' \
-d '{
    "pluginName": "divide",
    "selectorHandler": "[{\"upstreamUrl\":\"192.168.10.100:8000\"}]",
    "conditionDataList": [{
        "paramType": "uri",
        "operator": "match",
        "paramValue": "/**"
    }],
    "ruleDataList": [{
        "ruleHandler": "{\"loadBalance\":\"random\"}",
        "conditionDataList": [{
            "paramType": "uri",
            "operator": "match",
            "paramValue": "/**"
        }]
    }]
}'

#message
success
```

### Error

- curl
```bash
curl localhost:9195/ken
```
- message
```json
{"code":-106,"message":"Can not find url, please check your configuration!"}
```

### Reference
- https://github.com/apache/shenyu?tab=readme-ov-file#quick-start-docker

### Image Information

```
REPOSITORY                TAG       IMAGE ID       CREATED        SIZE
apache/shenyu-bootstrap   latest    41272da53c70   4 months ago   332MB
```

**Comment by yu199195** [comment]
show log

**Comment by geek-ken** [comment]
It seems that Shenyu needs to connect to Shenyu-admin, but the wiki does not mention it.
```
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.Socket.connect(Socket.java:589)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
        at java.lang.Thread.run(Thread.java:748)
2023-12-12 08:57:59 [shenyu-shared_wheel_timer-4] WARN  org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket connection server[ws://localhost:9095/websocket] is error.....
2023-12-12 08:58:09 [WebSocketConnectReadThread-417] ERROR org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket server[ws://localhost:9095/websocket] is error.....
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.Socket.connect(Socket.java:589)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
        at java.lang.Thread.run(Thread.java:748)
2023-12-12 08:58:09 [shenyu-shared_wheel_timer-4] WARN  org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - websocket connection server[ws://localhost:9095/websocket] is error.....
```
I recreated the container using this：
```
sudo docker network create shenyu-quickstart
sudo docker run -d --name shenyu-admin-quickstart \
           -p 9095:9095        \
           --network=shenyu-quickstart     \
           apache/shenyu-admin

sudo docker run -d --name shenyu-quickstart \
           -p 9195:9195        \
           -e "shenyu.local.enabled=true" \
           -e SHENYU_SYNC_WEBSOCKET_URLS=ws://shenyu-admin-quickstart:9095/websocket \
           --network=shenyu-quickstart     \
           apache/shenyu-bootstrap
```
Now,it's OK.

**Comment by geek-ken** [comment]
It's fixed by：https://github.com/apache/shenyu/pull/5353
