### ISSUE TITLE
check zombie upstream the url=xxxx.xx.xx.xx:9090 is fail

### ISSUE THREAD

**Issue by Tiberiusjhh** [apache/shenyu#5605]
### Question

admin.   24-08-03 00:20:36 [shenyu-upstream-health-check-request-6] ERROR org.apache.shenyu.common.utils.UpstreamCheckUtils - socket connect is error. host:192.168.50.88 port:9090 timeout:3000
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)

**Comment by Aias00** [comment]
hi，the Upstream Check function is just creating a TCP socket connection. so if it can not connect successfully, may be u have to check your client or the network status.
