### ISSUE TITLE
[Question] <title>client cannot connect to interface

### ISSUE THREAD

**Issue by ColdFragrance** [apache/shenyu#5666]
### Question

Hi everyone.My project built by shenyu-bootstrap,When the client frequently calls the interface in a short period of time, there are often individual request timeouts, and the call logs cannot be seen in shenyu. However, at this time, most requests are normal.
Look forward to your reply

**Comment by Aias00** [comment]
more details, such as log, pls?

**Comment by ColdFragrance** [comment]
logs of client calls imp as follows:
`[2024-09-19 22:31:17] [hystrix-imp-5] [DEBUG] [c.b.m.a.AClient:72] -- [AClient#downloadFileList] ---> POST https://imp/imp/tgz/download-file-list HTTP/1.1
[2024-09-19 22:31:17] [hystrix-imp-5] [DEBUG] [c.b.m.a.AClient:72] -- [AClient#downloadFileList] Accept: application/json
[2024-09-19 22:31:17] [hystrix-imp-5] [DEBUG] [c.b.m.a.AClient:72] -- [AClient#downloadFileList] Content-Length: 31
[2024-09-19 22:31:17] [hystrix-imp-5] [DEBUG] [c.b.m.a.AClient:72] -- [AClient#downloadFileList] Content-Type: application/json
[2024-09-19 22:31:17] [hystrix-imp-5] [DEBUG] [c.b.m.a.AClient:72] -- [AClient#downloadFileList] 
[2024-09-19 22:31:17] [hystrix-imp-5] [DEBUG] [c.b.m.a.AClient:72] -- [AClient#downloadFileList] {"uId":"67068772525164548"}
[2024-09-19 22:31:17] [hystrix-imp-5] [DEBUG] [c.b.m.a.AClient:72] -- [AClient#downloadFileList] ---> END HTTP (31-byte body)
[2024-09-19 22:32:07] [HystrixTimer-1] [ERROR] [c.b.m.a.AClientFallbackFactory:28] -- 异常原因:null
com.netflix.hystrix.exception.HystrixTimeoutException: null
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.run(AbstractCommand.java:1142)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:37)
	at com.alibaba.cloud.seata.feign.hystrix.SeataHystrixConcurrencyStrategy$SeataContextCallable.call(SeataHystrixConcurrencyStrategy.java:163)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:57)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$2.tick(AbstractCommand.java:1159)
	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[2024-09-19 22:32:07] [http-nio-9150-exec-1] [INFO ] [c.b.a.s.i.AServiceImpl:164] -- 服务端超时: 熔断保护：服务间访问超时
[2024-09-19 22:32:07] [http-nio-9150-exec-1] [ERROR] [c.b.a.s.i.AServiceImpl:184] -- 下载文件异常：
c.b.e.RestStatusException: null
	at com.boot.util.ShiftUtil.fatalThrow(ShiftUtil.java:32)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:901)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)`
 
imp (server side) has no any log.
