### ISSUE TITLE
[BUG] <Nacos data sync model missing the contextPath configuration>

### ISSUE THREAD

**Issue by Wweiei** [apache/shenyu#5721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the shenyu data synchronization chose the nacos model, if the nacos server contextPath is not the default /nacos, shenyu-admin or  shenyu-bootstrap will be unable to connect to the nacos. And the server will start failed due to the failure of connect to nacos.

For example:
nacos server config:
![image](https://github.com/user-attachments/assets/a4360e5c-e917-41db-af62-fa973d232eab)
nacos login path:
![image](https://github.com/user-attachments/assets/08766a63-76c4-430a-a0c8-de8d29da6189)
shenyu-admin config:
![image](https://github.com/user-attachments/assets/8b0d9706-2e1b-4aa0-b52f-1a24e9b8ec45)
In current shenyu nacos config, there is no parameter to configure /nacoslocal. and the nacos client will use the default value /nacos. The nacos login verification will fail due to incorrect address when Shenyu-admin or Shenyu-bootstrap starts.
![image](https://github.com/user-attachments/assets/68e54311-c696-4258-b987-2eb90868886a)
![image](https://github.com/user-attachments/assets/b31639d1-eb47-41bb-bea6-a5f12d873a5c)

### Expected Behavior

shenyu.sync.nacos should have a parameter to set the contextPath. and then nacos-client can connect to nacos successfully.

### Steps To Reproduce

1.check out to master branch and pull the lastest code.
2.prepare a Nacos service with the contextPath set to a value other than /nacos.
3.change shenyu-admin shenyu.sync.nacos's config in application.yml

### Environment

```markdown
ShenYu version(s):branch master latest
```

### Debug logs

``` Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-10-25 16:26:44 [main] ERROR com.alibaba.nacos.client.auth.impl.process.HttpLoginProcessor - login failed: {"code":404,"message":"<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Language":"en","Content-Length":"431","Content-Type":"text/html;charset=utf-8","Date":"Fri, 25 Oct 2024 08:26:44 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Language":["en"],"Content-Length":["431"],"Content-Type":["text/html;charset=utf-8"],"Date":["Fri, 25 Oct 2024 08:26:44 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF-8"}}
2024-10-25 16:26:44 [main] INFO  com.alibaba.nacos.client.auth.ram.identify.CredentialWatcher - null No credential found
2024-10-25 16:26:44 [com.alibaba.nacos.client.Worker] ERROR com.alibaba.nacos.client.auth.impl.process.HttpLoginProcessor - login failed: {"code":404,"message":"<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Language":"en","Content-Length":"431","Content-Type":"text/html;charset=utf-8","Date":"Fri, 25 Oct 2024 08:26:44 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Language":["en"],"Content-Length":["431"],"Content-Type":["text/html;charset=utf-8"],"Date":["Fri, 25 Oct 2024 08:26:44 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF-8"}}

2024-10-25 16:26:48 [main] ERROR org.apache.shenyu.admin.listener.nacos.NacosDataChangedInit - Get data from nacos error.
com.alibaba.nacos.api.exception.NacosException: http error, code=403,msg=user not found!,dataId=plugin.list,group=DEFAULT_GROUP,tenant=local_weiwei
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:1094)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:443)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:184)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:96)
	at org.apache.shenyu.admin.listener.nacos.NacosDataChangedInit.dataIdNotExist(NacosDataChangedInit.java:62)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
	at org.apache.shenyu.admin.listener.nacos.NacosDataChangedInit.notExist(NacosDataChangedInit.java:56)
	at org.apache.shenyu.admin.listener.AbstractDataChangedInit.run(AbstractDataChangedInit.java:38)
	at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790)
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83)
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789)
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at org.apache.shenyu.admin.ShenyuAdminBootstrap.main(ShenyuAdminBootstrap.java:36)
 ```

### Anything else?

After add the contextPath parameter in org.apache.shenyu.admin.config.properties.NacosProperties and org.apache.shenyu.sync.data.nacos.config.NacosConfig, then add the CONTEXT_PATH property for the ConfigService , shenyu-admin and shenyu-bootstrap can start successfully. And shenyu-admin can push data to nacos successfully, or shenyu-bootstrap pull data from nacos successfully.

**Comment by moremind** [comment]
thanks for your suggest, this bug has fixed in #5722
