### ISSUE TITLE
[BUG] An InaccessibleObjectException was thrown during startup.

### ISSUE THREAD

**Issue by Saoforest** [apache/shenyu#5752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An InaccessibleObjectException was thrown when the application started.

### Environment

```markdown
ShenYu version(s): origin/master
JDK: 21
```

### Debug logs

Exception in thread "Thread-5" java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.util.IdentityHashMap java.lang.ApplicationShutdownHooks.hooks accessible: module java.base does not "opens java.lang" to unnamed module @3327bd23
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
	at org.apache.shenyu.client.core.shutdown.ShenyuClientShutdownHook$TakeoverOtherHooksThread.run(ShenyuClientShutdownHook.java:89)

**Comment by yu199195** [comment]
only support jdk 17

**Comment by Saoforest** [comment]
> only support jdk 17
> 
> you can add this jvm param
> 
> ```
> --add-opens java.base/java.lang=ALL-UNNAMED
> ```

The specific business application integrated with the Shenyu gateway also only supports JDK17 and below?
